version: '3.8'

services:
  app:
    build: https://github.com/twuijri/atayb.git
    container_name: atayb
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - atayb-uploads:/app/public/uploads
      - atayb-data:/app/data
    environment:
      - NODE_ENV=production

volumes:
  atayb-uploads:
  atayb-data:
