version: '3.8'

services:
  app:
    image: node:20-alpine
    container_name: atayb
    restart: unless-stopped
    working_dir: /app
    command: >
      sh -c "
      apk add --no-cache git &&
      rm -rf /tmp/repo &&
      git clone https://github.com/twuijri/atayb.git /tmp/repo &&
      cp -r /tmp/repo/. /app/ &&
      rm -rf /tmp/repo &&
      mkdir -p /app/data /app/public/uploads &&
      if [ ! -f /app/data/config.json ]; then
        echo '{\"adminUsername\":\"admin\",\"adminPassword\":\"password\"}' > /app/data/config.json;
      fi &&
      npm ci &&
      npm run build &&
      node .next/standalone/server.js
      "
    ports:
      - "3000:3000"
    volumes:
      - atayb-uploads:/app/public/uploads
      - atayb-data:/app/data
    environment:
      - NODE_ENV=production

volumes:
  atayb-uploads:
  atayb-data:
