version: '3.8'

services:
  app:
    image: node:20-alpine
    container_name: link-manager-app
    restart: unless-stopped
    working_dir: /app
    command:
      - sh
      - -c
      - |
        apk add --no-cache git
        git clone https://${GITHUB_TOKEN}@github.com/twuijri/atayb.git /tmp/repo
        cp -r /tmp/repo/. /app/
        rm -rf /tmp/repo
        mkdir -p /app/data
        if [ ! -f /app/data/config.json ]; then
          echo '{"adminUsername":"admin","adminPassword":"password"}' > /app/data/config.json
        fi
        rm -rf /app/.next
        npm ci
        npm run build
        node .next/standalone/server.js
    ports:
      - "3000:3000"
    volumes:
      - link-manager-uploads:/app/public/uploads
      - link-manager-data:/app/data
    environment:
      - NODE_ENV=production
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    networks:
      - link-manager-network

volumes:
  link-manager-uploads:
  link-manager-data:

networks:
  link-manager-network:
